Mobile first project "My Portfolio"
Pi1998/my-portfolio pull request #1
Opened 2023-04-26 15:38 UTC by Pi1998

# Branch Changes 👍 

- Added a .gitignore file 💯
- Added node_modules and test.md to gitignore file 👍
- Set up linter for HTML and CSS 👮‍♂️
- Updated README file 📚
- Created HTML and CSS files 📁
- Two sections with a menu button and the first page of the project (mobile version) 📃 
- CSS styling which includes font styling, color, alignment of texts, and background image 🥇 
- Social media icons and down-arrow button ⏹️

2023-04-26 17:14 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @Pi1998 , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- Your Readme file looks very professionally. ✔
- You used GitHub flow correctly. ✔
- Your commit messages are meaningful and descriptive. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 17:14 UTC, ridwanediallo commented on portfolio.html
> +                </span>
- [ ] For semantic reasons, I would suggest moving the text  `I'm a software developer` outside of the `h1` and wrapping it with the `p` tag instead of a `span`. Then, using CSS, you can style it to look like the template. :ok_hand:

2023-04-26 17:14 UTC, ridwanediallo commented on portfolio.css
> +h1 {
- [ ] Please use this `#172B4D` colour for this `h1` because it's one used on the template. 😊

2023-04-26 17:14 UTC, ridwanediallo commented on portfolio.html
> +            </p>
- [ ] Please for this paragraph use this `#172B4D` colour instead because it's one used on the template. 😊

2023-04-27 05:49 UTC, merged

2023-04-27 05:57 UTC, topeogunleye reviewed
Hi @Pi1998,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a merged pull request, Kindly make sure you do not merge your PR until it is approved. Please revert your merge.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.